# docker-compose.yml
# Add this top-level entry
version: "3"
services:
  mariadb:
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    image: mariadb-records:latest
    container_name: cougar-grades.mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  redis:
    image: redis:5.0-alpine
    container_name: cougar-grades.cache
    expose:
      - 6379
  webserver:
    build: ./webserver
    container_name: cougar-grades.webserver
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mariadb
    environment:
      - NODE_ENV=${NODE_ENV}
      - WEBSERVER_BASEURL=${WEBSERVER_BASEURL}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
